import { StyleSheet, Dimensions } from 'react-native';
import { theme } from '@tarodan/ui-native';

const { colors } = theme;
const { width } = Dimensions.get('window');
export const CARD_WIDTH = (width - 48) / 2;

// Route-local stylesheet (§12). Monolitten BİREBİR taşındı.
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.surface.alt },
  searchSection: {
    backgroundColor: colors.surface.DEFAULT,
    paddingHorizontal: theme.spacing[4],
    paddingVertical: theme.spacing[3],
    borderBottomWidth: 1,
    borderBottomColor: colors.border.DEFAULT,
  },
  searchBar: { marginBottom: theme.spacing[3] },
  actionRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  sortButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: theme.spacing[2],
    paddingHorizontal: theme.spacing[3],
    borderRadius: theme.radius.xl,
    backgroundColor: colors.surface.alt,
  },
  sortButtonText: { marginLeft: theme.spacing[1.5], fontSize: 13, color: colors.text.muted },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: theme.spacing[2],
    paddingHorizontal: theme.spacing[3],
    borderRadius: theme.radius.xl,
    backgroundColor: colors.surface.alt,
  },
  filterButtonText: { marginLeft: theme.spacing[1.5], fontSize: 13, color: colors.text.muted },
  filterBadge: {
    marginLeft: theme.spacing[1.5],
    backgroundColor: colors.primary[600]!,
    borderRadius: theme.radius['2xl'],
    paddingHorizontal: theme.spacing[1.5],
    paddingVertical: theme.spacing[0.5],
  },
  filterBadgeText: { fontSize: 11, fontWeight: 'bold', color: colors.white },
  chipsRow: { backgroundColor: colors.surface.DEFAULT, maxHeight: 56, flexGrow: 0 },
  chipsContent: { paddingHorizontal: theme.spacing[4], paddingVertical: theme.spacing[3], gap: theme.spacing[2], alignItems: 'center' },
  sortBackdrop: { flex: 1, backgroundColor: colors.overlay.black50, justifyContent: 'flex-end' },
  sortSheet: {
    backgroundColor: colors.surface.DEFAULT,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: theme.spacing[5],
    paddingBottom: theme.spacing[10],
  },
  sortHandle: {
    width: 40,
    height: 4,
    backgroundColor: colors.border.DEFAULT,
    borderRadius: theme.radius.sm,
    alignSelf: 'center',
    marginBottom: theme.spacing[4],
  },
  sortTitle: { fontSize: 18, fontWeight: 'bold', color: colors.text.heading, marginBottom: theme.spacing[2] },
  sortOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: theme.spacing[3.5],
    borderBottomWidth: 1,
    borderBottomColor: colors.border.subtle,
  },
  sortOptionText: { fontSize: 15, color: colors.text.heading },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  loadingText: { marginTop: theme.spacing[3], color: colors.text.muted },
  emptyContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: theme.spacing[8], paddingTop: theme.spacing[20] },
  emptyTitle: { marginTop: theme.spacing[4], fontSize: 18, fontWeight: 'bold', color: colors.text.heading },
  emptySubtitle: { marginTop: theme.spacing[2], fontSize: 14, color: colors.text.muted, textAlign: 'center' },
  listingsContent: { padding: theme.spacing[4] },
  listRow: { justifyContent: 'space-between' },
  resultsCount: { fontSize: 13, color: colors.text.muted, marginBottom: theme.spacing[3] },
  productCard: {
    width: CARD_WIDTH,
    backgroundColor: colors.surface.DEFAULT,
    borderRadius: 12,
    overflow: 'hidden',
    marginBottom: theme.spacing[4],
    elevation: 2,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  productImageContainer: { position: 'relative' },
  productImage: { width: '100%', height: CARD_WIDTH * 0.9, backgroundColor: colors.surface.alt },
  tradeBadge: {
    position: 'absolute',
    top: 8,
    left: 8,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.success[500]!,
    paddingHorizontal: theme.spacing[2],
    paddingVertical: theme.spacing[1],
    borderRadius: theme.radius.md,
  },
  tradeBadgeText: { marginLeft: theme.spacing[1], fontSize: 11, fontWeight: 'bold', color: colors.white },
  productContent: { padding: theme.spacing[3] },
  productTitle: { fontSize: 13, fontWeight: '600', color: colors.text.heading, marginBottom: theme.spacing[1] },
  productMeta: { fontSize: 11, color: colors.text.muted, marginBottom: theme.spacing[2] },
  priceRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  productPrice: { fontSize: 16, fontWeight: 'bold', color: colors.primary[600]! },
  conditionBadge: {
    fontSize: 10,
    color: colors.text.muted,
    backgroundColor: colors.surface.alt,
    paddingHorizontal: theme.spacing[1.5],
    paddingVertical: theme.spacing[0.5],
    borderRadius: theme.radius.md,
  },
});
