import { StyleSheet } from 'react-native';
import { theme } from '@tarodan/ui-native';

import { quickActionTint } from './profileConstants';

const { colors, spacing, radius } = theme;

// Profil ekranının route-local stylesheet'i (monolitten birebir taşındı).
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.surface.alt,
  },
  header: {
    backgroundColor: colors.primary[600]!,
    paddingTop: 50,
    paddingBottom: spacing[4],
    paddingHorizontal: spacing[5],
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  scrollView: { flex: 1 },
  guestWelcome: {
    backgroundColor: colors.surface.DEFAULT,
    margin: spacing[4],
    padding: spacing[6],
    borderRadius: radius['3xl'],
    alignItems: 'center',
    elevation: 2,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  loginButton: { width: '100%', marginBottom: spacing[3] },
  registerButton: { width: '100%' },
  benefitsSection: {
    paddingHorizontal: spacing[4],
    marginTop: spacing[2],
  },
  benefitCard: {
    flexDirection: 'row',
    backgroundColor: colors.surface.DEFAULT,
    borderRadius: radius['2xl'],
    padding: spacing[4],
    marginBottom: spacing[3],
  },
  benefitIcon: {
    width: 48,
    height: 48,
    borderRadius: radius.full,
    justifyContent: 'center',
    alignItems: 'center',
  },
  benefitContent: {
    flex: 1,
    marginLeft: spacing[3],
  },
  quickLinksSection: {
    marginTop: spacing[6],
    paddingHorizontal: spacing[4],
  },
  quickLinkItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface.DEFAULT,
    padding: spacing[4],
    borderRadius: radius['2xl'],
    marginBottom: spacing[2],
  },
  quickLinkText: {
    flex: 1,
    marginLeft: spacing[3],
  },
  premiumPromo: {
    margin: spacing[4],
    padding: spacing[6],
    backgroundColor: colors.gray[800],
    borderRadius: radius['3xl'],
  },
  premiumHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing[3],
  },
  premiumPrice: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginBottom: spacing[4],
  },
  profileCard: {
    backgroundColor: colors.surface.DEFAULT,
    margin: spacing[4],
    padding: spacing[5],
    borderRadius: radius['3xl'],
    flexDirection: 'row',
    alignItems: 'center',
    elevation: 2,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  profileInfo: {
    flex: 1,
    marginLeft: spacing[4],
  },
  membershipBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface.alt,
    paddingHorizontal: spacing[2.5],
    paddingVertical: spacing[1],
    borderRadius: radius['2xl'],
    marginTop: spacing[2],
    alignSelf: 'flex-start',
  },
  trustRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: spacing[2],
    marginTop: spacing[1.5],
  },
  trustBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.warning[50]!,
    paddingHorizontal: spacing[2.5],
    paddingVertical: spacing[1],
    borderRadius: radius['2xl'],
  },
  trustToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing[2],
    paddingVertical: spacing[1],
    borderRadius: radius['2xl'],
    backgroundColor: colors.surface.alt,
    borderWidth: 1,
    borderColor: colors.border.DEFAULT,
  },
  editButton: { padding: spacing[2] },
  statsGrid: {
    flexDirection: 'row',
    marginHorizontal: spacing[4],
    backgroundColor: colors.surface.DEFAULT,
    borderRadius: radius['3xl'],
    padding: spacing[4],
    elevation: 2,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  statItem: {
    flex: 1,
    alignItems: 'center',
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  section: {
    marginTop: spacing[6],
    paddingHorizontal: spacing[4],
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing[3],
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  garageCard: {
    backgroundColor: colors.surface.DEFAULT,
    borderRadius: radius['3xl'],
    padding: spacing[6],
    alignItems: 'center',
    borderWidth: 2,
    borderColor: colors.border.DEFAULT,
    borderStyle: 'dashed',
  },
  garageScroll: {
    paddingRight: spacing[4],
    gap: spacing[3],
  },
  collectionCard: {
    width: 140,
  },
  collectionImageWrap: {
    width: 140,
    height: 100,
    borderRadius: radius['2xl'],
    overflow: 'hidden',
    backgroundColor: colors.surface.alt,
  },
  collectionImage: {
    width: '100%',
    height: '100%',
  },
  privateBadge: {
    position: 'absolute',
    top: spacing[2],
    right: spacing[2],
    width: 24,
    height: 24,
    borderRadius: radius.full,
    backgroundColor: colors.overlay.black50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  collectionAddCard: {
    width: 100,
    height: 100,
    borderRadius: radius['2xl'],
    borderWidth: 2,
    borderColor: colors.border.DEFAULT,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: spacing[3],
  },
  quickAction: {
    alignItems: 'center',
    width: '33.333%',
    paddingHorizontal: spacing[1],
    marginBottom: spacing[4],
  },
  quickActionIcon: {
    width: 52,
    height: 52,
    borderRadius: radius.full,
    backgroundColor: quickActionTint.bg,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing[2],
  },
  quickActionLabel: {
    minHeight: 32,
  },
  menuSection: {
    marginTop: spacing[6],
    paddingHorizontal: spacing[4],
  },
  menuItem: {
    backgroundColor: colors.surface.DEFAULT,
    flexDirection: 'row',
    alignItems: 'center',
    padding: spacing[4],
    borderRadius: radius['2xl'],
    marginBottom: spacing[2],
  },
  menuItemText: {
    flex: 1,
    marginLeft: spacing[3],
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: spacing[4],
    marginTop: spacing[6],
    padding: spacing[4],
    borderRadius: radius['2xl'],
    backgroundColor: colors.surface.DEFAULT,
    borderWidth: 1,
    borderColor: colors.danger[600]!,
  },
  deleteAccountButton: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: spacing[3],
    padding: spacing[2],
  },
});
