import { StyleSheet } from 'react-native';
import { theme } from '@tarodan/ui-native';

import { CARD_WIDTH } from './searchConstants';

const { colors, radius } = theme;

// Arama ekranının route-local stylesheet'i (monolitten birebir taşındı).
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.surface.alt },
  header: {
    backgroundColor: colors.primary[600]!,
    paddingTop: 50,
    paddingBottom: theme.spacing[4],
    paddingHorizontal: theme.spacing[5],
  },
  headerTitle: { fontSize: 24, fontWeight: 'bold', color: colors.white },
  // Sonuç alanı: absolute üst çubukları barındırır; yukarı kayan çubukları kırpar.
  resultsArea: { flex: 1, position: 'relative', overflow: 'hidden' },
  // Üst çubuklar (arama + filtre + çipler + sayım) — absolute katman, liste üstünde durur.
  collapsibleBars: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 30,
    backgroundColor: colors.surface.DEFAULT,
  },
  searchSection: {
    padding: theme.spacing[4],
    backgroundColor: colors.surface.DEFAULT,
    position: 'relative',
    zIndex: 10,
  },
  searchAnchor: {
    position: 'relative',
    zIndex: 20,
  },
  searchInputContainer: {
    marginBottom: theme.spacing[0],
  },
  searchInputField: {
    borderColor: colors.primary[600]!,
    borderWidth: 1.5,
  },
  searchInputFieldOpen: {
    borderBottomLeftRadius: theme.radius.none,
    borderBottomRightRadius: theme.radius.none,
  },
  recentSearchesDropdown: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    marginTop: -1,
    backgroundColor: colors.white,
    borderTopLeftRadius: theme.radius.none,
    borderTopRightRadius: theme.radius.none,
    borderBottomLeftRadius: radius.xl,
    borderBottomRightRadius: radius.xl,
    borderTopWidth: 0,
    borderLeftWidth: 1.5,
    borderRightWidth: 1.5,
    borderBottomWidth: 1.5,
    borderColor: colors.primary[600]!,
    elevation: 4,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    zIndex: 100,
  },
  acSection: {
    paddingTop: theme.spacing[2],
    paddingBottom: theme.spacing[1],
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border.subtle,
  },
  acSectionTitle: {
    paddingHorizontal: theme.spacing[4],
    paddingVertical: theme.spacing[1.5],
    fontSize: 11,
    fontWeight: '700',
    color: colors.text.subtle,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  acItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing[2.5],
    paddingHorizontal: theme.spacing[4],
    paddingVertical: theme.spacing[2.5],
  },
  acItemText: { fontSize: 14, color: colors.text.heading, flex: 1 },
  acItemMeta: { fontSize: 11, color: colors.text.muted, marginTop: theme.spacing[0.5] },
  recentSearchesHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: theme.spacing[4],
    paddingVertical: theme.spacing[3],
    borderBottomWidth: 1,
    borderBottomColor: colors.border.DEFAULT,
  },
  recentSearchesTitle: { fontSize: 14, fontWeight: '600', color: colors.text.heading },
  clearRecentText: { fontSize: 13, color: colors.primary[600]!, fontWeight: '500' },
  recentSearchItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: theme.spacing[4],
    paddingVertical: theme.spacing[3],
    borderBottomWidth: 1,
    borderBottomColor: colors.border.DEFAULT,
  },
  recentSearchText: { flex: 1, marginLeft: theme.spacing[3], fontSize: 14, color: colors.text.heading },
  filterRow: {
    flexDirection: 'row',
    paddingHorizontal: theme.spacing[4],
    paddingVertical: theme.spacing[3],
    backgroundColor: colors.surface.DEFAULT,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.DEFAULT,
  },
  filterButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: theme.spacing[2.5],
    marginHorizontal: theme.spacing[2],
    backgroundColor: colors.surface.alt,
    borderRadius: theme.radius.xl,
  },
  filterButtonText: { marginLeft: theme.spacing[2], fontSize: 14, fontWeight: '500', color: colors.text.heading },
  filterBadge: {
    marginLeft: theme.spacing[1.5],
    backgroundColor: colors.primary[600]!,
    borderRadius: theme.radius['2xl'],
    minWidth: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterBadgeText: { fontSize: 12, fontWeight: 'bold', color: colors.white },
  quickFilters: { backgroundColor: colors.surface.DEFAULT, maxHeight: 56 },
  quickFiltersContent: {
    paddingHorizontal: theme.spacing[4],
    paddingVertical: theme.spacing[3],
    gap: theme.spacing[2],
    alignItems: 'center',
  },
  activeChip: { marginRight: theme.spacing[2], backgroundColor: colors.primary[50]! },
  resultsCount: { paddingHorizontal: theme.spacing[4], paddingVertical: theme.spacing[2], backgroundColor: colors.surface.alt },
  resultsCountText: { fontSize: 13, color: colors.text.muted },
  listContent: { padding: theme.spacing[4], paddingTop: theme.spacing[2] },
  listRow: { justifyContent: 'space-between' },
  scrollTopFab: {
    position: 'absolute',
    right: 16,
    bottom: 24,
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.primary[600]!,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 6,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
    zIndex: 50,
  },
  productCardWrapper: { width: CARD_WIDTH, marginBottom: theme.spacing[4] },
  productCard: {
    overflow: 'hidden',
    backgroundColor: colors.surface.DEFAULT,
    elevation: 2,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  imageWrap: { position: 'relative' },
  productImage: { height: CARD_WIDTH },
  inCartPill: {
    position: 'absolute',
    bottom: 8,
    left: 8,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.primary[600]!,
    paddingHorizontal: theme.spacing[2],
    paddingVertical: theme.spacing[1],
    borderRadius: theme.radius.xl,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  tradeBadge: {
    position: 'absolute',
    top: 8,
    left: 8,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.success[500]!,
    paddingHorizontal: theme.spacing[2],
    paddingVertical: theme.spacing[1],
    borderRadius: 12,
  },
  conditionBadge: {
    position: 'absolute',
    top: 8,
    right: 8,
    paddingHorizontal: theme.spacing[2],
    paddingVertical: theme.spacing[1],
    borderRadius: 12,
  },
  productContent: { paddingVertical: theme.spacing[3] },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  loadingText: { marginTop: theme.spacing[3], fontSize: 14, color: colors.text.muted },
  emptyContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingVertical: 60 },
  emptyTitle: { fontSize: 18, fontWeight: 'bold', color: colors.text.heading, marginTop: theme.spacing[4] },
  emptySubtitle: { fontSize: 14, color: colors.text.muted, textAlign: 'center', marginTop: theme.spacing[2] },
  sortModalBackdrop: {
    flex: 1,
    backgroundColor: colors.overlay.black50,
    justifyContent: 'flex-end',
  },
  sortModalContent: {
    backgroundColor: colors.surface.DEFAULT,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: theme.spacing[5],
    paddingBottom: theme.spacing[10],
  },
  sortModalHandle: {
    width: 40,
    height: 4,
    backgroundColor: colors.border.DEFAULT,
    borderRadius: theme.radius.sm,
    alignSelf: 'center',
    marginBottom: theme.spacing[4],
  },
  sortModalTitle: { fontSize: 18, fontWeight: 'bold', color: colors.text.heading, marginBottom: theme.spacing[4] },
  sortOption: { flexDirection: 'row', alignItems: 'center', paddingVertical: theme.spacing[3] },
  sortOptionText: { flex: 1, fontSize: 16, color: colors.text.heading, marginLeft: theme.spacing[3] },
});
