// Home ekranının stilleri — orijinal (tabs)/index.tsx'ten birebir taşındı.
import { StyleSheet, Dimensions } from 'react-native';
import { theme } from '@tarodan/ui-native';

const { colors } = theme;
const { width } = Dimensions.get('window');
export const CARD_WIDTH = (width - 48) / 2;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.surface.DEFAULT,
  },
  header: {
    backgroundColor: colors.primary[600]!,
    paddingTop: 50,
    paddingHorizontal: theme.spacing[4],
    paddingBottom: theme.spacing[5],
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: theme.spacing[4],
  },
  logo: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.white,
  },
  logoAccent: {
    color: colors.gray[200],
  },
  headerActions: {
    flexDirection: 'row',
    backgroundColor: colors.overlay.white20,
    borderRadius: 14,
    padding: theme.spacing[1.5],
    gap: theme.spacing[2],
  },
  headerIconBtn: {
    width: 40,
    height: 40,
    borderRadius: theme.radius['2xl'],
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.overlay.white10,
  },
  headerBadge: {
    position: 'absolute',
    top: -6,
    right: -6,
    minWidth: 20,
    height: 20,
    borderRadius: theme.radius['2xl'],
    paddingHorizontal: 5,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: colors.primary[600]!,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.18,
    shadowRadius: 2,
    elevation: 3,
  },
  headerBadgeText: {
    color: colors.primary[700]!,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 14,
    textAlign: 'center',
  },
  inCartPill: {
    position: 'absolute',
    bottom: 8,
    left: 8,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.primary[600]!,
    paddingHorizontal: theme.spacing[2],
    paddingVertical: theme.spacing[1],
    borderRadius: theme.radius.xl,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  searchBar: {
    backgroundColor: colors.surface.DEFAULT,
    borderRadius: 12,
    elevation: 2,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  searchInput: {
    fontSize: 14,
    color: colors.text.heading,
  },
  scrollView: {
    flex: 1,
  },
  heroBanner: {
    marginHorizontal: theme.spacing[4],
    marginTop: -10,
    marginBottom: theme.spacing[2],
    borderRadius: 20,
    overflow: 'hidden',
    elevation: 4,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
  },
  heroGradient: {
    padding: theme.spacing[6],
  },
  heroContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  heroText: {
    flex: 1,
  },
  heroTitle: {
    fontSize: 16,
    fontWeight: '500',
    color: colors.text.muted,
    marginBottom: theme.spacing[1],
  },
  heroSubtitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.text.heading,
    marginBottom: theme.spacing[2.5],
  },
  heroDescription: {
    fontSize: 13,
    color: colors.text.muted,
    marginBottom: theme.spacing[5],
    lineHeight: 20,
  },
  heroButtons: {
    flexDirection: 'row',
    gap: theme.spacing[2.5],
  },
  heroButtonPrimary: {
    backgroundColor: colors.primary[600]!,
    paddingHorizontal: 18,
    paddingVertical: theme.spacing[3],
    borderRadius: theme.radius['2xl'],
  },
  heroButtonPrimaryText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.white,
  },
  heroButtonSecondary: {
    backgroundColor: colors.surface.DEFAULT,
    paddingHorizontal: 18,
    paddingVertical: theme.spacing[3],
    borderRadius: theme.radius['2xl'],
    borderWidth: 1.5,
    borderColor: colors.border.DEFAULT,
  },
  heroButtonSecondaryText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.text.heading,
  },
  heroImage: {
    width: 100,
    height: 100,
  },
  section: {
    marginBottom: 28,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: theme.spacing[4],
    marginBottom: theme.spacing[4],
  },
  sectionTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sectionIndicator: {
    width: 4,
    height: 24,
    backgroundColor: colors.primary[600]!,
    borderRadius: theme.radius.sm,
    marginRight: theme.spacing[2.5],
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.text.heading,
    letterSpacing: -0.3,
  },
  seeAllText: {
    fontSize: 14,
    color: colors.primary[600]!,
    fontWeight: '600',
  },
  brandsScroll: {
    paddingLeft: theme.spacing[4],
  },
  brandItem: {
    marginRight: theme.spacing[2.5],
  },
  brandLogo: {
    backgroundColor: colors.surface.DEFAULT,
    borderWidth: 1.5,
    borderColor: colors.border.DEFAULT,
    borderRadius: 12,
    paddingHorizontal: theme.spacing[5],
    paddingVertical: theme.spacing[3.5],
    minWidth: 90,
    alignItems: 'center',
    elevation: 1,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  brandLogoText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.text.heading,
  },
  scalesScroll: {
    paddingLeft: theme.spacing[4],
  },
  scaleChip: {
    backgroundColor: colors.primary[50]!,
    borderWidth: 1.5,
    borderColor: colors.primary[600]!,
    borderRadius: 24,
    paddingHorizontal: 18,
    paddingVertical: theme.spacing[2.5],
    marginRight: theme.spacing[2.5],
  },
  scaleChipText: {
    fontSize: 14,
    color: colors.primary[600]!,
    fontWeight: '600',
  },
  collectorCard: {
    backgroundColor: colors.surface.DEFAULT,
    marginHorizontal: theme.spacing[4],
    borderRadius: 12,
    padding: theme.spacing[4],
    borderWidth: 1,
    borderColor: colors.border.DEFAULT,
  },
  collectorInfo: {
    flexDirection: 'row',
    marginBottom: theme.spacing[4],
  },
  collectorDetails: {
    flex: 1,
    marginLeft: theme.spacing[3],
  },
  collectorName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.text.heading,
  },
  collectorDesc: {
    fontSize: 12,
    color: colors.text.muted,
    marginTop: theme.spacing[1],
  },
  collectorStats: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: theme.spacing[2],
  },
  collectorStatText: {
    fontSize: 12,
    color: colors.text.muted,
    marginLeft: theme.spacing[1],
  },
  viewGarageButton: {
    marginTop: theme.spacing[2],
  },
  viewGarageButtonText: {
    fontSize: 13,
    color: colors.text.heading,
    fontWeight: '500',
    borderWidth: 1,
    borderColor: colors.border.DEFAULT,
    borderRadius: theme.radius.lg,
    paddingHorizontal: theme.spacing[3],
    paddingVertical: theme.spacing[1.5],
    alignSelf: 'flex-start',
  },
  collectorProducts: {
    marginTop: theme.spacing[2],
  },
  bestSellersSection: {
    backgroundColor: colors.primary[600]!,
    paddingVertical: theme.spacing[6],
    borderRadius: theme.radius.none,
  },
  productsScroll: {
    paddingLeft: theme.spacing[4],
  },
  productCardWrapper: {
    width: CARD_WIDTH * 0.9,
    marginRight: theme.spacing[3.5],
  },
  productCard: {
    marginRight: theme.spacing[0],
    backgroundColor: colors.surface.DEFAULT,
    borderRadius: theme.radius['3xl'],
    overflow: 'hidden',
    elevation: 3,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
  },
  productImageContainer: {
    position: 'relative',
    width: '100%',
  },
  productImage: {
    width: '100%',
    height: 140,
    backgroundColor: colors.gray[200],
  },
  topLeftStack: {
    position: 'absolute',
    top: 10,
    left: 10,
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: theme.spacing[1.5],
  },
  badge: {
    alignSelf: 'flex-start',
    paddingHorizontal: theme.spacing[2.5],
    paddingVertical: 5,
    borderRadius: theme.radius.lg,
    flexDirection: 'row',
    alignItems: 'center',
  },
  badgeText: {
    fontSize: 11,
    fontWeight: 'bold',
    color: colors.white,
  },
  likesContainer: {
    position: 'absolute',
    top: 10,
    right: 10,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.overlay.white95,
    paddingHorizontal: theme.spacing[2],
    paddingVertical: theme.spacing[1],
    borderRadius: theme.radius.xl,
  },
  likesText: {
    fontSize: 12,
    color: colors.text.muted,
    marginLeft: theme.spacing[1],
    fontWeight: '500',
  },
  productContent: {
    padding: theme.spacing[3.5],
  },
  productTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text.heading,
    marginBottom: theme.spacing[1.5],
    lineHeight: 20,
  },
  productMeta: {
    fontSize: 12,
    color: colors.text.muted,
    marginBottom: theme.spacing[2],
  },
  productPrice: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.primary[700]!,
  },
  companyDetails: {
    flex: 1,
    marginLeft: theme.spacing[3],
  },
  companyName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.text.heading,
  },
  companyDesc: {
    fontSize: 12,
    color: colors.text.muted,
    marginTop: theme.spacing[1],
  },
  companyMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: theme.spacing[2],
    gap: theme.spacing[4],
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  ratingText: {
    fontSize: 12,
    color: colors.text.muted,
    marginLeft: theme.spacing[1],
  },
  verifiedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  verifiedText: {
    fontSize: 12,
    color: colors.info[600]!,
    marginLeft: theme.spacing[1],
  },
  companyProducts: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  companyProductItem: {
    width: '48%',
    marginBottom: theme.spacing[3],
  },
  categoryCount: {
    fontSize: 10,
    color: colors.text.muted,
    marginTop: theme.spacing[0.5],
  },
  loadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 50,
  },
  loadingText: {
    color: colors.overlay.white90,
    marginTop: theme.spacing[3.5],
    fontSize: 15,
    fontWeight: '500',
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 50,
  },
  emptyText: {
    color: colors.overlay.white90,
    marginTop: theme.spacing[3.5],
    fontSize: 18,
    fontWeight: '700',
  },
  emptySubtext: {
    color: colors.overlay.white70,
    marginTop: theme.spacing[1.5],
    fontSize: 14,
  },
  productsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: theme.spacing[3],
    justifyContent: 'space-between',
  },
  gridItem: {
    width: '48%',
    marginBottom: theme.spacing[3.5],
  },
  collectionCard: {
    width: 170,
    marginRight: theme.spacing[3.5],
    backgroundColor: colors.surface.DEFAULT,
    borderRadius: theme.radius['3xl'],
    overflow: 'hidden',
    elevation: 3,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
  },
  collectionImage: {
    width: '100%',
    height: 110,
    backgroundColor: colors.gray[200],
  },
  collectionInfo: {
    padding: theme.spacing[3],
  },
  collectionName: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text.heading,
  },
  collectionMeta: {
    fontSize: 12,
    color: colors.text.muted,
    marginTop: theme.spacing[1],
  },
  featuredCard: {
    backgroundColor: colors.surface.DEFAULT,
    marginHorizontal: theme.spacing[4],
    borderRadius: 20,
    padding: 18,
    elevation: 3,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    borderWidth: 1,
    borderColor: colors.primary[200]!,
  },
  featuredHeader: {
    flexDirection: 'row',
    marginBottom: 18,
  },
  featuredAvatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: colors.primary[600]!,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: colors.primary[200]!,
  },
  featuredAvatarText: {
    fontSize: 26,
    fontWeight: 'bold',
    color: colors.white,
  },
  featuredInfo: {
    flex: 1,
    marginLeft: theme.spacing[3.5],
    justifyContent: 'center',
  },
  featuredName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text.heading,
  },
  featuredDesc: {
    fontSize: 13,
    color: colors.text.muted,
    marginTop: theme.spacing[1],
  },
  featuredStats: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: theme.spacing[2],
    backgroundColor: colors.primary[50]!,
    alignSelf: 'flex-start',
    paddingHorizontal: theme.spacing[2.5],
    paddingVertical: theme.spacing[1],
    borderRadius: theme.radius.xl,
  },
  featuredStatText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.primary[600]!,
    marginLeft: theme.spacing[1],
  },
  featuredProducts: {
    marginBottom: theme.spacing[3.5],
  },
  featuredProductCard: {
    width: 140,
    marginRight: theme.spacing[3],
    backgroundColor: colors.surface.alt,
    borderRadius: 14,
    overflow: 'hidden',
  },
  featuredProductImage: {
    width: '100%',
    height: 110,
    backgroundColor: colors.gray[200],
  },
  featuredProductTitle: {
    fontSize: 13,
    fontWeight: '500',
    color: colors.text.heading,
    padding: theme.spacing[2.5],
    paddingBottom: theme.spacing[1],
  },
  featuredProductPrice: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.primary[700]!,
    paddingHorizontal: theme.spacing[2.5],
    paddingBottom: theme.spacing[2.5],
  },
  viewGarageBtn: {
    alignSelf: 'flex-start',
    backgroundColor: colors.primary[50]!,
    paddingHorizontal: theme.spacing[4],
    paddingVertical: theme.spacing[2.5],
    borderRadius: theme.radius['2xl'],
  },
  viewGarageBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.primary[600]!,
  },
  companyMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: theme.spacing[1.5],
    gap: theme.spacing[3],
  },
  ratingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  ratingBadgeText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.text.heading,
    marginLeft: theme.spacing[1],
  },
  verifiedBadgeSmall: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  verifiedBadgeSmallText: {
    fontSize: 12,
    color: colors.success[600]!,
    marginLeft: theme.spacing[1],
  },
  // Logo styles
  logoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logoImage: {
    width: 130,
    height: 42,
    marginRight: theme.spacing[1],
  },
  // Company Section styles - Modern design
  companySection: {
    backgroundColor: colors.primary[50]!,
    paddingVertical: theme.spacing[6],
    marginBottom: theme.spacing[6],
  },
  businessBadge: {
    backgroundColor: colors.primary[600]!,
    paddingHorizontal: theme.spacing[2.5],
    paddingVertical: 5,
    borderRadius: 14,
    marginLeft: theme.spacing[2.5],
  },
  businessBadgeText: {
    fontSize: 11,
    fontWeight: 'bold',
    color: colors.white,
  },
  companyCard: {
    backgroundColor: colors.white,
    marginHorizontal: theme.spacing[4],
    borderRadius: 20,
    padding: theme.spacing[5],
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 5,
    borderWidth: 1,
    borderColor: colors.primary[200]!,
  },
  companyHeader: {
    flexDirection: 'row',
    marginBottom: 18,
  },
  companyAvatar: {
    width: 70,
    height: 70,
    borderRadius: 35,
    borderWidth: 3,
    borderColor: colors.primary[200]!,
  },
  companyAvatarGradient: {
    width: 70,
    height: 70,
    borderRadius: 35,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: colors.primary[200]!,
  },
  companyAvatarText: {
    fontSize: 28,
    fontWeight: 'bold',
    color: colors.white,
  },
  companyInfo: {
    flex: 1,
    marginLeft: theme.spacing[3.5],
    justifyContent: 'center',
  },
  companyNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing[2],
  },
  companyNameText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.text.heading,
  },
  companyBio: {
    fontSize: 13,
    color: colors.text.muted,
    marginTop: theme.spacing[1.5],
    lineHeight: 18,
  },
  companyStatsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: theme.spacing[2.5],
    marginBottom: theme.spacing[4],
  },
  companyStat: {
    flex: 1,
    minWidth: '45%',
    borderRadius: 12,
    padding: theme.spacing[3],
    alignItems: 'center',
  },
  companyStatValue: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  companyStatLabel: {
    fontSize: 11,
    color: colors.text.muted,
    marginTop: theme.spacing[1],
    fontWeight: '500',
  },
  companyRating: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: theme.spacing[3.5],
    backgroundColor: colors.warning[50]!,
    alignSelf: 'flex-start',
    paddingHorizontal: theme.spacing[3],
    paddingVertical: theme.spacing[1.5],
    borderRadius: theme.radius['2xl'],
  },
  companyRatingValue: {
    fontSize: 15,
    fontWeight: 'bold',
    color: colors.text.heading,
    marginLeft: theme.spacing[1.5],
  },
  companyRatingCount: {
    fontSize: 13,
    color: colors.text.muted,
    marginLeft: theme.spacing[1.5],
  },
  companySectionTitle: {
    fontSize: 17,
    fontWeight: 'bold',
    color: colors.text.heading,
    marginBottom: theme.spacing[3.5],
    marginTop: theme.spacing[3],
  },
  companyProductsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: theme.spacing[2.5],
  },
  companyProductCard: {
    width: '31%',
    backgroundColor: colors.surface.alt,
    borderRadius: 14,
    overflow: 'hidden',
  },
  companyProductImage: {
    width: '100%',
    height: 85,
    backgroundColor: colors.gray[200],
  },
  companyProductLikes: {
    position: 'absolute',
    top: 6,
    left: 6,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.overlay.white95,
    paddingHorizontal: theme.spacing[2],
    paddingVertical: 3,
    borderRadius: theme.radius.lg,
  },
  companyProductLikesText: {
    fontSize: 11,
    fontWeight: '700',
    marginLeft: 3,
    color: colors.primary[600]!,
  },
  companyProductInfo: {
    padding: theme.spacing[2.5],
  },
  companyProductTitle: {
    fontSize: 12,
    fontWeight: '500',
    color: colors.text.heading,
    marginBottom: theme.spacing[1.5],
    lineHeight: 16,
  },
  companyProductPrice: {
    fontSize: 14,
    fontWeight: 'bold',
    color: colors.primary[700]!,
  },
  companyCollectionCard: {
    flexDirection: 'row',
    backgroundColor: colors.surface.alt,
    borderRadius: 14,
    padding: theme.spacing[3.5],
    marginBottom: theme.spacing[2.5],
    alignItems: 'center',
  },
  companyCollectionImage: {
    width: 60,
    height: 60,
    borderRadius: theme.radius['2xl'],
    backgroundColor: colors.gray[200],
  },
  companyCollectionImagePlaceholder: {
    width: 60,
    height: 60,
    borderRadius: theme.radius['2xl'],
    backgroundColor: colors.gray[200],
    justifyContent: 'center',
    alignItems: 'center',
  },
  companyCollectionInfo: {
    flex: 1,
    marginLeft: theme.spacing[3.5],
  },
  companyCollectionName: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.text.heading,
  },
  companyCollectionMeta: {
    fontSize: 13,
    color: colors.text.muted,
    marginTop: theme.spacing[1],
  },
  companyCollectionStats: {
    flexDirection: 'row',
    gap: theme.spacing[3.5],
    marginTop: theme.spacing[1.5],
  },
  companyCollectionStatText: {
    fontSize: 12,
    color: colors.info[600]!,
    fontWeight: '500',
  },
  companyCollectionStatTextRed: {
    fontSize: 12,
    color: colors.danger[600]!,
    fontWeight: '500',
  },
  viewStoreButton: {
    marginTop: 18,
  },
  viewStoreButtonGradient: {
    paddingVertical: theme.spacing[3.5],
    borderRadius: 12,
    alignItems: 'center',
  },
  viewStoreButtonText: {
    fontSize: 15,
    fontWeight: 'bold',
    color: colors.white,
  },
});
