/**
 * Codegen: derive the `MessageKey` union from the catalog so `t()` / consumers
 * get compile-time key autocomplete and typos fail to build. Regenerate with
 * `pnpm --filter @tarodan/i18n codegen`; CI (typecheck) fails if it is stale.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const trFile = resolve(here, '../src/catalog/tr.json');
const outFile = resolve(here, '../src/generated/keys.ts');

/** Collect every leaf dot-path key from a nested message object. */
export function flatten(obj, prefix = '', out = []) {
  for (const [k, v] of Object.entries(obj)) {
    const key = prefix ? `${prefix}.${k}` : k;
    if (v && typeof v === 'object' && !Array.isArray(v)) flatten(v, key, out);
    else out.push(key);
  }
  return out;
}

/** The exact content the generated keys file should have. */
export function buildKeysFile() {
  const tr = JSON.parse(readFileSync(trFile, 'utf8'));
  const keys = flatten(tr).sort();
  const union = keys.map((k) => `  | ${JSON.stringify(k)}`).join('\n');
  return (
    `// AUTO-GENERATED by scripts/gen-keys.mjs — do not edit by hand.\n` +
    `// Regenerate: pnpm --filter @tarodan/i18n codegen\n\n` +
    `/** Every dot-path key in the catalog (${keys.length} keys). */\n` +
    `export type MessageKey =\n${union};\n`
  );
}

// When run directly, write the file.
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const content = buildKeysFile();
  mkdirSync(dirname(outFile), { recursive: true });
  writeFileSync(outFile, content);
  console.log(`generated ${outFile} (${content.split('\n').length - 1} lines)`);
}
